name: "🐛 Bug Report"
description: "If something isn't working as expected 🤔."
title: "[Bug]: "
labels: ["needs triage", "bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a bug report! Please fill out this form as completely as possible.

  - type: checkboxes
    id: input1
    attributes:
      label: "💻"
      options:
        - label: Would you like to work on a fix?

  - type: textarea
    attributes:
      label: Input code
      description: You must write here the minimal input code necessary to reproduce the bug.
      placeholder: |
        ```js
        new Stack(app, "Stack", {});
        ```
    validations:
      required: true

  - type: textarea
    attributes:
      label: Current and expected behavior
      description: A clear and concise description of what Babel is doing and what you would expect.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      placeholder: |
        - Astro AWS version(s):
        - Astro version(s):
        - Node:
        - npm/Yarn version: [e.g. npm 7/Yarn 2.3]
        - AWS CDK version(s):
    validations:
      required: true

  - type: textarea
    attributes:
      label: Possible solution
      description: "If you have suggestions on a fix for the bug."

  - type: textarea
    attributes:
      label: Additional context
      description: "Add any other context about the problem here. Or a screenshot if applicable."
