function mapToRegExp(str: string) {
	return new RegExp(`^${str.toLowerCase()}$`, "u")
}

const READ_ONLY_HEADERS = [
	"Connection",
	"Content-Length",
	"Expect",
	"Keep-Alive",
	"Proxy-Authenticate",
	"Proxy-Authorization",
	"Proxy-Connection",
	"Trailer",
	"Upgrade",
	"X-Accel-Buffering",
	"X-Accel-Charset",
	"X-Accel-Limit-Rate",
	"X-Accel-Redirect",
	"X-Amz-Cf-.*",
	"X-Amzn-Auth",
	"X-Amzn-Cf-Billing",
	"X-Amzn-Cf-Id",
	"X-Amzn-Cf-Xff",
	"X-Amzn-Errortype",
	"X-Amzn-Fle-Profile",
	"X-Amzn-Header-Count",
	"X-Amzn-Header-Order",
	"X-Amzn-Lambda-Integration-Tag",
	"X-Amzn-RequestId",
	"X-Cache",
	"X-Edge-.*",
	"X-Forwarded-Proto",
	"X-Real-IP",
]

const READ_ONLY_ORIGIN_REQUEST_HEADERS = [
	...READ_ONLY_HEADERS,
	"Accept-Encoding",
	"If-Modified-Since",
	"If-None-Match",
	"If-Range",
	"If-Unmodified-Since",
	"Transfer-Encoding",
	"Via",
].map(mapToRegExp)

const READ_ONLY_ORIGIN_RESPONSE_HEADERS = [
	...READ_ONLY_HEADERS,
	"Transfer-Encoding",
	"Via",
].map(mapToRegExp)

const KNOWN_BINARY_MEDIA_TYPES = [
	"application/epub+zip",
	"application/java-archive",
	"application/msword",
	"application/octet-stream",
	"application/pdf",
	"application/rtf",
	"application/vnd.amazon.ebook",
	"application/vnd.apple.installer+xml",
	"application/vnd.ms-excel",
	"application/vnd.ms-powerpoint",
	"application/vnd.openxmlformats-officedocument.presentationml.presentation",
	"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
	"application/vnd.openxmlformats-officedocument.wordprocessingml.document",
	"application/x-7z-compressed",
	"application/x-apple-diskimage",
	"application/x-bzip",
	"application/x-bzip2",
	"application/x-gzip",
	"application/x-java-archive",
	"application/x-rar-compressed",
	"application/x-tar",
	"application/x-zip",
	"application/zip",
	"audio/3gpp",
	"audio/aac",
	"audio/basic",
	"audio/mpeg",
	"audio/ogg",
	"audio/wavaudio/webm",
	"audio/x-aiff",
	"audio/x-midi",
	"audio/x-wav",
	"font/otf",
	"font/woff",
	"font/woff2",
	"image/bmp",
	"image/gif",
	"image/jpeg",
	"image/png",
	"image/tiff",
	"image/vnd.microsoft.icon",
	"image/webp",
	"video/3gpp",
	"video/mp2t",
	"video/mpeg",
	"video/ogg",
	"video/quicktime",
	"video/webm",
	"video/x-msvideo",
]

export {
	READ_ONLY_ORIGIN_REQUEST_HEADERS,
	READ_ONLY_ORIGIN_RESPONSE_HEADERS,
	KNOWN_BINARY_MEDIA_TYPES,
}
