name: CD - Prod

on:
  workflow_dispatch:

env:
  CI: true
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

permissions:
  id-token: write
  contents: read
  deployments: write

jobs:
  deploy-prod:
    name: Deploy Prod
    concurrency:
      group: ${{ format('{0}-{1}', github.workflow, github.job) }}
    uses: ./.github/workflows/deploy.yml
    with:
      environment_name: production
      environment_url: https://www.docs.astro-aws.org/
      stack_environment: PROD
    secrets: inherit
