name: CD

on:
  workflow_dispatch:

env:
  CI: true
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

permissions:
  id-token: write
  contents: read
  deployments: write

jobs:
  prepare-yarn-cache:
    name: Cache dependencies
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
      - run: yarn install --mode=skip-build
        env:
          YARN_ENABLE_SCRIPTS: false
  deploy-prod:
    name: Deploy Prod
    needs: [prepare-yarn-cache]
    concurrency:
      group: ${{ format('{0}-{1}', github.workflow, github.job) }}
    uses: ./.github/workflows/deploy.yml
    with:
      environment_name: production
      environment_url: https://astro-aws.org/
      stack_environment: PROD
    secrets: inherit
